### ISSUE TITLE
Cannot run SDRenderTweaker

### ISSUE THREAD

**Issue by Armanello** [sneakyevil/SD-RenderTweaker#11]
I've put mod files in game folder and getting this error message when trying to run game
![Снимок](https://github.com/sneakyevil/SD-RenderTweaker/assets/92509884/d539e124-91f2-4734-a454-a636ab4e550b)

**Comment by sneakyevil** [comment]
Literally says you what to do, visit that site and read `README.md` which is literally pinned at that page.

**Comment by sneakyevil** [comment]
> @sneakyevil I read the readme file, I'm confused, that page explains how to create mods for the game. At the top of the page there's a tip section containing an exe (Compatibility game executable), is that what is needed for this mod to work? If so I think instructions could be more explicit that you need a custom/patched exe. Moreover, who patched it? Is it you, or is this taken from somewhere else?

There is nothing patched in the exe, is still has original digital signature by square enix that's still valid. It's just due to that they shipped debug symbols with first release of the steam version and then later on rebuild it and shipped new same exe with changed addresses so the debug symbols won't match the new exe. Also the render tweaker itself will show error message that the executable of the game isn't valid.
