### ISSUE TITLE
[Resquest] Better refresh rate detection or workaround to force an specific hertz rate

### ISSUE THREAD

**Issue by serveral1** [sneakyevil/SD-RenderTweaker#21]
Currently the game has this issue where it automatically assigns the highest refresh rate that your GPU can output to a given resolution (in my case it's forcing the 1360x768 resolution to be locked at 170hz, even though in W10's display settings it's set to 60hz) making it impossible to play on fullscreen else the monitor will give you an "signal out of range" message.

Could it be possible to fix the game's refresh rate detection or make it so that one can force an specific hz value, or would that be something that's out of the scope of this project?

Also I'm aware there are solutions like Borderless Gaming and AHK scripts, etc, but in my experience all those workarounds end up with the window being stretched out, with the textures and text in-game looking all blurry.

**Comment by sneakyevil** [comment]
This shouldn't even be needed to be implemented as the game config already has such option and just requires some tweaking to get it right.

Inside game there is folder called `data` which contain file named `DisplaySettings.xml`.
This file contain XML information for display settings and the one you're looking for is `RefreshRateNumerator` and `RefreshRateDenominator`.

You could try changing numerator to `60000` and denominator to `1001` which would effectively should run the game at 59.94Hz. 
You might need to try and run each time the game with different numbers if it even works since this is entirely different for each monitor, perhaps there is some program that will give you list of your resolutions with numerator & denominator.
