### ISSUE TITLE
Camera Auto-Center while Walking/Sprinting

### ISSUE THREAD

**Issue by Fukojin** [sneakyevil/SD-RenderTweaker#4]
The camera auto corrects to face the same direction as the player character when trying to move one way while looking in another. It's slight when walking but more aggressive when sprinting. Extending the "Disable Vehicle Auto Center" feature to Wei Shen would be great. Thank you for your generous mod support for this amazing game.

https://github.com/sneakyevil/SD-RenderTweaker/assets/155631687/b2e82c45-70e9-4ddf-8107-310e70da4b32

In the clip above I am constantly resisting the camera to make it not face in the direction I'm sprinting in.

**Comment by sneakyevil** [comment]
This might be already option in the game, you might try it and tell me if it works. Under `Game and Controls Options` there is option called `Mouse Free Look` seems like I have that thing by default on and I couldn't replicate same issue as you have besides I turned it off. Let me know if turning that on does solve this issue, besides you're playing on controller.

**Comment by Fukojin** [comment]
I have that on and I am on M+KB. To try and replicate the issue try running forward while looking back, in my case the camera keeps trying to slowly rotating forward in the direction of the sprint.


https://github.com/sneakyevil/SD-RenderTweaker/assets/155631687/ad721495-64b7-4c63-b56a-98771d93059c

In this clip I'm pressing "Forward+Left" Movement key while trying to pan the camera right but it keeps resisting to pan left instead.

**Comment by sneakyevil** [comment]
I don't have such issue, are you sure you don't have any controller or anything plugged in that could cause this issue?
There isn't anything that would resist me from moving camera even while moving, here is videos with the free look on/off and you can clearly see that the camera doesn't rotate at all besides it slightly moves due to player movement, but rotation is still same.

With `Mouse Free Look` enabled:

https://github.com/sneakyevil/SD-RenderTweaker/assets/29150970/e6d82901-4587-4ef1-b326-98639184ac08

With `Mouse Free Look` disabled:

https://github.com/sneakyevil/SD-RenderTweaker/assets/29150970/ef625b2d-db6c-4e3b-a609-dc0ea0eca461

**Comment by Fukojin** [comment]
In your first clip you aren't panning your mouse WHILE moving. If you would like a live explanation maybe we can get in touch on discord but if not try doing what I did in the description below the last clip I shared

**Comment by sneakyevil** [comment]
As I said even with panning there isn't any issue, I just provided video where I don't move mouse at all since that could explain it more, but here is another video even with moving. If you think that the camera is trying to rotate to center and it's resisting that isn't even camera issue, but that's normal player behavior following movement based on camera rotation and you think it is centering while it isn't.

https://github.com/sneakyevil/SD-RenderTweaker/assets/29150970/a540bdb8-e323-47a5-801a-447717b31e79

**Comment by Fukojin** [comment]
Alright, I think you are correct in the fact that it's the player movement causing the camera to feel that way. In my opinion if that effect could be disabled or even lowered the game would feel a lot better especially sprinting. Because trying to turn the mouse while sprinting feels like the camera is constantly resisting the input from the mouse. Here's a clip showing that.

https://github.com/sneakyevil/SD-RenderTweaker/assets/155631687/5ef1b63b-b738-46ae-83d6-15fc80d9306a

**Comment by sneakyevil** [comment]
This can't really be tweaked by any means, is literally player input and there isn't anything I could "fix" that. Like imagine you have point of view of your head and you have direction you going forward when you rotate your head it would go basically to that direction if you want to keep moving to same direction as you started it would need to be offset by original head rotation which literally means I would need to write some sort of logic that would constantly check if player stopped moving camera & started moving -> save rotation and now I would need to constantly give different rotation input to the game based on player input with old rotation which is literally something that I'm not willing to implement in Render Tweaker and even if I wanted to implement it as additional plugin it will be just time consuming to even get it somehow working without totally breaking player input.
